CREATE TABLE STUDENT(
	RNO INT,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50)
)
CREATE TABLE RESULT(
	RNO INT,
	SPI DECIMAL(4,2),
)
CREATE TABLE EMPLOYEE1(
	EMPLOYEENO VARCHAR(50),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(50)
)
INSERT INTO STUDENT VALUES
--(101,'RAJU','CE'),
(102,'AMIT','CE'),
(103,'SANJAY','ME'),
(104,'NEHA','EC'),
(105,'MEERA','EE'),
(106,'MAHES','ME')

INSERT INTO RESULT VALUES
--(101,8.8),
(102,9.2),
(103,7.6),
(104,8.2),
(105,7.0),
(107,8.9)

INSERT INTO EMPLOYEE1 VALUES
--('E01','TARUN',NULL)
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

--1
SELECT * FROM STUDENT CROSS JOIN RESULT

--2
SELECT STUDENT.RNO,STUDENT.NAME,STUDENT.BRANCH,RESULT.SPI
FROM STUDENT INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH='CE'

--3
SELECT STUDENT.RNO,STUDENT.NAME,STUDENT.BRANCH,RESULT.SPI
FROM STUDENT LEFT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH<>'EC'

--4
SELECT  STUDENT.BRANCH,AVG(RESULT.SPI)
FROM STUDENT INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
GROUP BY STUDENT.BRANCH

--5
SELECT  STUDENT.BRANCH,AVG(RESULT.SPI)
FROM STUDENT INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY AVG(RESULT.SPI)

--6
SELECT  STUDENT.BRANCH,AVG(RESULT.SPI)
FROM STUDENT INNER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH='CE' OR STUDENT.BRANCH='ME'
GROUP BY STUDENT.BRANCH

--7
SELECT *
FROM STUDENT LEFT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO

--8
SELECT *
FROM STUDENT RIGHT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO

--9
SELECT * 
FROM STUDENT FULL OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO

